Don't sleep any more than we need to ...
... to prevent the bot from spamming a given table with lots of actions.  (If someone is observing that table in their
browser, they can miss events, since it seems the browser takes a while to respond to each event.)

Alas I often see

   sqlite3.OperationalError: disk I/O error

from either the bot, or generate_fake_data (I forget which), despite my having sprinkled a lot of "retry"s here and there.

https://docs.djangoproject.com/en/5.1/ref/databases/#database-is-locked-errors suggests that I "Switch... to another
database backend." 😢