Apparantly, tests now depend on "collectstatic" 🤷
Otherwise I get

    ValueError: Missing staticfiles manifest entry ...

... despite the "shaddap_complaints_about_missing_staticfiles_manifest_entries" fixture in conftest.py 🤷🤷🤷