Try a fresh fixture for one test.
  20:12:05 8581810240 DEBUG tournament.py 310 next_movement_round Imagine I checked all my tables (<QuerySet [Table #1 in tournament #1]>), and if they were all complete, destroying them and creating new ones
  ==================================================================== short test summary info =====================================================================
  FAILED app/test_hand_events.py::test_sends_new_hand_event_to_table_channel - app.models.table.NoMoreBoards: find_unplayed_board returned None; I'm no longer sure what that means